apiVersion: v1
kind: Pod
metadata:
  name: demo-java-app
  namespace: applications
  labels:
    app: demo-java-app
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  restartPolicy: Never
  volumes:
  - name: shared-ai-agent
    emptyDir: {}
  initContainers:
  - name: ai-init-container
    image: [Docker Image Registry URL]/ai-init-container
    resources:
      requests:
        cpu: 250m
      limits:
        cpu: 500m
        memory: 250Mi
    volumeMounts:
    - name: shared-ai-agent
      mountPath: /shared-ai-agent/    
  containers:
  - name: demo-java-app
    image: [Docker Image Registry URL]/demo-java-ai
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 250m
      limits:
        cpu: 500m
        memory: 250Mi
    env:
    - name: APPLICATION_INSIGHTS_IKEY
      value: "[AppInsights IKEY]"
    - name: _JAVA_OPTIONS
      value: "-javaagent:/shared-ai-agent/applicationinsights-agent.jar -DapplicationInsights.configurationFile=/shared-ai-agent/ApplicationInsights.json"
    volumeMounts:
    - name: shared-ai-agent
      mountPath: /shared-ai-agent/
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-app
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-java-app