apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-java-app
  namespace: applications
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: demo-java-app
        image: [Docker Image Registry URL]/demo-java-ai
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: APPLICATION_INSIGHTS_IKEY
          value: "[AppInsights IKEY]"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-app
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-java-app